name: agconnect_crash_plus
description: 由于华为flutter开发人员及其不爱维护,自己来更新,Flutter plugin for AppGallery Connect Crash SDK.
version: 3.0.0
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-crash-introduction

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectcrash
        pluginClass: AGConnectCrashPlugin
      ios:
        pluginClass: AGConnectCrashPlugin
